### ISSUE TITLE
getting config exception in lambda..

### ISSUE THREAD

**Issue by PramodBisht** [rackerlabs/lambda-uploader#110]
Hi there,

I am getting below given exception on triggering lambda which is uploaded thru lambda-uploader.

The specified config file (/home/sbx_user1051/.aws/config) could not be found.: ConfigNotFound
Traceback (most recent call last):
s3 = boto3.client('s3')
File "/var/task/boto3/__init__.py", line 79, in client
return _get_default_session().client(*args, **kwargs)
File "/var/task/boto3/__init__.py", line 69, in _get_default_session
setup_default_session()
File "/var/task/boto3/__init__.py", line 33, in setup_default_session
DEFAULT_SESSION = Session(**kwargs)
File "/var/task/boto3/boto3/session.py", line 80, in __init__
self._setup_loader()
File "/var/task/boto3/boto3/session.py", line 112, in _setup_loader
self._loader = self._session.get_component('data_loader')
File "/var/task/botocore/session.py", line 691, in get_component
return self._components.get_component(name)
File "/var/task/botocore/session.py", line 885, in get_component
self._components[name] = factory()
File "/var/task/botocore/session.py", line 179, in <lambda>
lambda: create_loader(self.get_config_variable('data_path')))
File "/var/task/botocore/session.py", line 259, in get_config_variable
elif self._found_in_config_file(methods, var_config):
File "/var/task/botocore/session.py", line 280, in _found_in_config_file
return var_config[0] in self.get_scoped_config()
File "/var/task/botocore/session.py", line 342, in get_scoped_config
profile_map = self._build_profile_map()
File "/var/task/botocore/session.py", line 214, in _build_profile_map
self._profile_map = self.full_config['profiles']
File "/var/task/botocore/session.py", line 369, in full_config
self._config = botocore.configloader.load_config(config_file)
File "/var/task/botocore/botocore/configloader.py", line 105, in load_config
parsed = raw_config_parse(config_filename)
File "/var/task/botocore/botocore/configloader.py", line 126, in raw_config_parse
raise botocore.exceptions.ConfigNotFound(path=path)
ConfigNotFound: The specified config file (/home/sbx_user1051/.aws/config) could not be found.

**Comment by jarosser06** [comment]
Interesting. What environment variables do you have set? This looks like boto3 is unable to get credentials for you and is defaulting to a config which also doesn't exist.

**Comment by PramodBisht** [comment]
started over again from installing requirements.txt to updating lambda.json, after that it worked fine.

**Comment by PramodBisht** [comment]
I don't know what I did wrong which caused this issue...:)

**Comment by jarosser06** [comment]
Glad to hear it has been resolved.
