### ISSUE TITLE
Exception: pip returned unsuccessfully

### ISSUE THREAD

**Issue by bittlingmayer** [rackerlabs/lambda-uploader#121]
I just saw this error:

> Adams-MacBook-Pro:lambda bittlingmayer$ lambda-uploader
> Î» Building Package
> âï¸ Unexpected error. Please report this traceback.
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/shell.py", line 173, in main
>     _execute(args)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/shell.py", line 73, in _execute
>     venv, cfg.ignore, extra_files)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/package.py", line 47, in build_package
>     pkg.build(ignore)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/package.py", line 68, in build
>     self.install_dependencies()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/package.py", line 141, in install_dependencies
>     self._install_requirements()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lambda_uploader/package.py", line 208, in _install_requirements
>     raise Exception('pip returned unsuccessfully')
> Exception: pip returned unsuccessfully

When I ran it again, there was no error, and the upload was successful.

pip is installed and working normally on my machine.

**Comment by martinb3** [comment]
Is this repeatable, or only happened once? We'd also need to see the output of trying to `pip install` the requirements for your project, as this exception is simply pip failing on your machine.

**Comment by jarosser06** [comment]
Along with what Martin mentioned we would need to see it run with Debug logs so we can see the pip failure.

**Comment by bittlingmayer** [comment]
I only saw it once.  May make sense to change that error message to also surface the error message from the pip failure, so that next dev who follows the instruction to report the stacktrace will include it by default.

**Comment by jarosser06** [comment]
I was thinking it may be beneficial to do that as well so I'll look at getting that changed.

**Comment by brandond** [comment]
Easy to reproduce by trying to install a C-based Python module without the appropriate libraries and/or headers installed.
