### ISSUE TITLE
Lambda-uploader faied on the first run

### ISSUE THREAD

**Issue by 2pvs** [rackerlabs/lambda-uploader#141]
PS C:\Users\Vladimir\Documents\Projects\df-cloud-platform\gordon-test\TaskManager-t> lambda-uploader
Building Package
âï¸ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\shell.py", line 182, in main
    _execute(args)
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\shell.py", line 77, in _execute
    venv, cfg.ignore, extra_files)
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\package.py", line 49, in build_package
    pkg.build(ignore)
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\package.py", line 77, in build
    self.package(ignore)
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\package.py", line 249, in package
    utils.copy_tree(self._path, package, ignore)
  File "c:\program files (x86)\python36-32\lib\site-packages\lambda_uploader\utils.py", line 54, in copy_tree
    shutil.copy(path, pkg_path)
  File "c:\program files (x86)\python36-32\lib\shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\program files (x86)\python36-32\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vladimir\\Documents\\Projects\\df-cloud-platform\\go
rdon-test\\TaskManager-t\\.lambda_uploader_temp\\lambda_package\\.lambda_uploader_temp\\venv\\Lib\\site-packages\\github
\\tests\\ReplayData\\Issue134.testGetAuthorizationsSucceedsWhenAutenticatedThroughLoginPassword.txt'

**Comment by jarosser06** [comment]
Can you provide the configuration file you used when running this. Also what version are you using?

**Comment by 2pvs** [comment]
Jim,
thank you for the prompt reply. Yes, it was the configuration file problem.
I managed to solve it.

**Comment by jarosser06** [comment]
Glad it got solved.
