### ISSUE TITLE
Botocore parameter validation errors

### ISSUE THREAD

**Issue by lyanez-sitecompli** [rackerlabs/lambda-uploader#150]
I encounter parameter validation errors and haven't found much help getting an answer anywhere.   My lambda.json file is as follows:
`{
  "name": "lambdaFunction",
  "description": "Function Description",
  "region": "us-east-1",
  "runtime": "python2.7",
  "handler": "lambda_function.lambda_handler",
  "role": "[ARNROLE]",
  "requirements": ["requests"],
  "ignore": [
    "circle\\.yml$",
    "\\.git$",
    "/.*\\.pyc$"
  ],
  "timeout": 30,
  "memory": 512
}`

`$ sudo lambda-uploader ./lambda --config ./lambda/lambda.json
λ Building Package
λ Uploading Package
⁉️ Unexpected error. Please report this traceback.
Uploader: 1.2.0
Botocore: 1.2.3
Boto3: 1.3.22

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lambda_uploader/shell.py", line 193, in main
    _execute(args)
  File "/usr/lib/python2.7/site-packages/lambda_uploader/shell.py", line 102, in _execute
    upldr.upload(pkg)
  File "/usr/lib/python2.7/site-packages/lambda_uploader/uploader.py", line 144, in upload
    self.version = self.upload_new(pkg)
  File "/usr/lib/python2.7/site-packages/lambda_uploader/uploader.py", line 121, in upload_new
    TracingConfig=self._config.tracing,
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 383, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 436, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 273, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "TracingConfig", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish
Unknown parameter in input: "VpcConfig", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish
Unknown parameter in input: "Environment", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish`

**Comment by jarosser06** [comment]
It looks like the versions you are using for botocore and boto3 are older than the minimum required versions. Try upgrading both of those to the minimum https://github.com/rackerlabs/lambda-uploader/blob/master/setup.py#L8-L9

**Comment by jarosser06** [comment]
Is there a particular reason you are running it with sudo? The credentials are likely not found because sudo doesn't usually default to using the user environment variables.
