### ISSUE TITLE
Issue building package

### ISSUE THREAD

**Issue by ElliotP123** [rackerlabs/lambda-uploader#154]
Evening,

I'm new to lambda functions and found this, it's an amazing tool. I just pip installed the latest version of lambda-uploader but I'm having trouble getting it to build the package.

I have saved my function.py (FundamentalHistorical.py -> Actual Name) at the root of the directory as well as my lambda.json file.

My lambda.json file is (edited out iam number): 
`{
  "name": "FundamentalHistoricalAustralia",
  "description": "It does things",
  "region": "ap-southeast-2",
  "runtime": "python3.6",
  "handler": "FundamentalHistoricalAustralia.lambda_handler",
  "role": "arn:aws:iam::85563:role/service-role/Admin",
  "requirements": ["pandas", "requests", "symtable", "datetime", "pyodbc", "sqlalchemy"],
  "ignore": [
    "circle\\.yml$",
    "\\.git$",
    "/.*\\.pyc$"
  ],
  "timeout": 300,
  "memory": 512,
  "vpc": {
    "subnets": [
      "subnet-00000000"
    ],
    "security_groups": [
      "sg-00000000"
    ]
  },
  "tracing": {
    "Mode": "Active"
  }
}`

This is the error it's now showing:
`(base) C:\Users\Elliot Parker>lambda-uploader ./
Building Package
â?ï¸ Unexpected error. Please report this traceback.
Uploader: 1.2.0
Botocore: 1.6.19
Boto3: 1.9.19

Traceback (most recent call last):
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\shell.py", line 1
93, in main
    _execute(args)
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\shell.py", line 8
4, in _execute
    venv, cfg.ignore, extra_files)
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\package.py", line
 49, in build_package
    pkg.build(ignore)
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\package.py", line
 75, in build
    self._prepare_workspace()
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\package.py", line
 161, in _prepare_workspace
    self.clean_workspace()
  File "d:\programs\anaconda\lib\site-packages\lambda_uploader\package.py", line
 82, in clean_workspace
    shutil.rmtree(self._temp_workspace)
  File "d:\programs\anaconda\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "d:\programs\anaconda\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "d:\programs\anaconda\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "d:\programs\anaconda\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Elliot Parker\\.lamb
da_uploader_temp\\lambda_package\\hwid'
`

I'm running the anaconda window with administrator privileges so I'm not sure now why there is an issue. Before the issue was that it was saying my lambda.json file was not a valid configuration file.

Thoughts?

**Comment by ElliotP123** [comment]
I seem to have solved it, but pandas is going well over the size limits.
