### ISSUE TITLE
Error when building example project

### ISSUE THREAD

**Issue by vcatalano** [rackerlabs/lambda-uploader#65]
When running `lambda-upload` on the example project, the follow exception occurs:

```python
λ Building Package
λ Uploading Package
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/lambda_uploader/shell.py", line 163, in main
    _execute(args)
  File "build/bdist.linux-x86_64/egg/lambda_uploader/shell.py", line 88, in _execute
    upldr.upload(pkg)
  File "build/bdist.linux-x86_64/egg/lambda_uploader/uploader.py", line 117, in upload
    self.version = self.upload_new(pkg)
  File "build/bdist.linux-x86_64/egg/lambda_uploader/uploader.py", line 80, in upload_new
    self._validate_package_size(pkg.zipfile)
AttributeError: 'Package' object has no attribute 'zipfile'
```

**Comment by jarosser06** [comment]
That was a bug I introduced. It should be fixed in master.

**Comment by jarosser06** [comment]
I stand corrected I missed one.

**Comment by jarosser06** [comment]
#66 Should fix your issue

**Comment by martinb3** [comment]
#66 has been merged.
