### ISSUE TITLE
Failing on bad execv() argument?

### ISSUE THREAD

**Issue by mxplusb** [rackerlabs/lambda-uploader#93]
I'm getting this traceback:

``` python
lambda-uploader --profile lambda-ops
λ Building Package
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/shell.py", line 172, in main
    _execute(args)
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/shell.py", line 73, in _execute
    venv, cfg.ignore, extra_files)
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/package.py", line 47, in build_package
    pkg.build(ignore)
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/package.py", line 68, in build
    self.install_dependencies()
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/package.py", line 138, in install_dependencies
    self._build_new_virtualenv()
  File "/Users/mikelloy/Library/Python/2.7/lib/python/site-packages/lambda_uploader/package.py", line 165, in _build_new_virtualenv
    self._pkg_venv], stdout=PIPE, stderr=PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Any ideas?

**Comment by martinb3** [comment]
Do you also have a JSON file for configuration? Could we see that too?

**Comment by jarosser06** [comment]
Can you run it with -VV and provide the output as well.
